### ISSUE TITLE
Exercise 1: Occurrence - Hash

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/ruby_track#1]
https://github.com/segunadeleye/ruby_track/blob/master/Ex1/lib/string.rb
https://github.com/segunadeleye/ruby_track/blob/master/Ex1/bin/main.rb

Count the ocurrences of various alphabet letters in an input string and store it in hash.

**Comment by Shruti2791** [comment]
We follow the below directory structure. Please follow this directory structure in all your ruby exercises.

```
Exercise
|__lib
     |__classes
|__bin
     |__main.rb

```

2) Why do we need to scan the string for the regex ?

**Comment by segunadeleye** [comment]
Fixed.

**Comment by Shruti2791** [comment]
2nd point not yet fixed. Why do we need regex ?

**Comment by segunadeleye** [comment]
Fixed

**Comment by Shruti2791** [comment]
Use require_relative instead of require. Read about their differences.
Else looks good.
