### ISSUE TITLE
Exercise 10: Hash - Inject

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/ruby_track#10]
https://github.com/segunadeleye/ruby_track/blob/master/Ex10/bin/main.rb
https://github.com/segunadeleye/ruby_track/blob/master/Ex10/lib/array.rb

Write a method that groups the above hash into 2 groups of 'even' and 'odd' length using 'inject'.Eg:
`['abc','def',1234,234,'abcd','x','mnop',5,'zZzZ'] -­> {odd: [["x", 5], ["abc", "def", 234]], even: [[1234, "abcd", "mnop", "zZzZ"]]}`

**Comment by mkangia** [comment]
Segun, filtering in two steps should not be needed. Please find a better shorter approach.

**Comment by segunadeleye** [comment]
Fixed!

**Comment by mkangia** [comment]
Segun we are doing two iterations again. Lets find a way to do this in a single iteration.
