### ISSUE TITLE
Exercise 14: Reverse Sentence

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/ruby_track#12]
https://github.com/segunadeleye/ruby_track/blob/master/Ex14/lib/string.rb
https://github.com/segunadeleye/ruby_track/blob/master/Ex14/bin/main.rb

Use string methods to reverse the words arrangement in a sentence. Eg:

`"An apple a day keeps the doctor away" -­> "away doctor the keeps day a apple An"`

**Comment by Shruti2791** [comment]
1) join, reverse and split can be combined into one line. Read about chaining in ruby. 
2) why reverse_sentence is the last line of the function ?

**Comment by segunadeleye** [comment]
Done.

**Comment by Shruti2791** [comment]
1) Use require_relative.
2) no need for 'reversed_sentence' variable.

**Comment by segunadeleye** [comment]
Fixed.

**Comment by Shruti2791** [comment]
looks good :+1:
