### ISSUE TITLE
Exercise 15: Prime Numbers - Step

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/ruby_track#13]
https://github.com/segunadeleye/ruby_track/blob/master/Ex15/bin/main.rb
https://github.com/segunadeleye/ruby_track/blob/master/Ex15/lib/fixnum.rb

Define a method to find all prime numbers upto `n` using 'step' function

**Comment by yuktikhurana** [comment]
1. Why 0..n ?
2. Can we use built in class ?
3. directory structure.

**Comment by segunadeleye** [comment]
Fixed. I used `Fixnum` class.

**Comment by yuktikhurana** [comment]
looks good
