### ISSUE TITLE
Exercise 16: Highlight Search Result

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/ruby_track#14]
https://github.com/segunadeleye/ruby_track/tree/master/Ex16/lib/string.rb
https://github.com/segunadeleye/ruby_track/tree/master/Ex16/bin/main.rb

Write a search method that searches for a letter or word in a user input string and highlights the searched element. Also it should display the total no of searches found.
Eg: If user enters string to be searched as `Can you can a can as a canner can can a can?` and word to be searched is `can` then output should be: `(Can) you (can) a (can) as a (can)ner (can) (can) a (can)? Total Occurences found: 7`

**Comment by abhishekjain16** [comment]
Use directory Structure as discussed

**Comment by abhishekjain16** [comment]
Too complex a method, We can do this with one loop/match itself.
if, gsub and scan all together not needed. Can be done by one loop itself.

**Comment by segunadeleye** [comment]
Fixed

**Comment by abhishekjain16** [comment]
For reference, Do not return string text like '#{self} | Total occurrences found: #{occurrence}' from method. We should always return changed string and count.
something like return [self, count]
In main.rb then we can always show user in whatever way we need to.

**Comment by abhishekjain16** [comment]
Closing for now, but remember above point

**Comment by segunadeleye** [comment]
Noted.

I'll correct that.
