### ISSUE TITLE
Exercise 11: Pascal - Yield

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/ruby_track#15]
https://github.com/segunadeleye/ruby_track/tree/master/Ex11/lib/fixnum.rb
https://github.com/segunadeleye/ruby_track/tree/master/Ex11/lib/pascal_triangle.rb
https://github.com/segunadeleye/ruby_track/tree/master/Ex11/bin/main.rb

Print Pascal's triangle using 'yield'.Eg:
`pascal(6)` gives: `1 1 1 1 2 1 1 3 3 1 1 4 6 4 1 1 5 10 10 5 1 1 6 15 20 15 6 1`

**Comment by Shruti2791** [comment]
Not working

**Comment by segunadeleye** [comment]
Fixed.
File path to fixnum.rb was wrong

**Comment by Shruti2791** [comment]
1) Keep proper variable names.

**Comment by segunadeleye** [comment]
Fixed

**Comment by Shruti2791** [comment]
Looks good :+1:
