### ISSUE TITLE
Exercise 17: Sum Time

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/ruby_track#16]
https://github.com/segunadeleye/ruby_track/blob/master/Ex17/lib/sum_time.rb
https://github.com/segunadeleye/ruby_track/tree/master/Ex17/bin/main.rb

Write a method that sums up 2 24­hour time values(h : m : s). Validate the time using regular expressions. Eg:
`("0:45:34","0:15:58")` ­-> `01:01:32`
`("11:23:07","22:53:45")` -­> `1 day & 10:16:52`

**Comment by mkangia** [comment]
Segun please optimise this method. Seems like a lot happening.
Also how about converting complete to seconds?

**Comment by segunadeleye** [comment]
Fixed
