### ISSUE TITLE
Exercise 19: Sum Time

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/ruby_track#17]
https://github.com/segunadeleye/ruby_track/blob/master/Ex19/lib/sum_time.rb
https://github.com/segunadeleye/ruby_track/tree/master/Ex19/bin/main.rb

Modify the sum of times method for any number of time values passed to this method. Eg:
`("11:23:07","22:53:45","0:23:23","23:45:56")` -­> `"2 day & 10:26:11"`
`("11:23:07")` ­-> `"11:23:07"`

**Comment by mkangia** [comment]
Please optimise the code. A lot happening in a single method.

**Comment by segunadeleye** [comment]
Fixed
