### ISSUE TITLE
Exercise 20: Interest Difference

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/ruby_track#18]
https://github.com/segunadeleye/ruby_track/blob/master/Ex20/lib/interest.rb
https://github.com/segunadeleye/ruby_track/tree/master/Ex20/bin/main.rb

Create a class Interest that gives the user the difference in amount calculated simply and compoundedly. Initialise class with a block. 'p' and 't' are entered by user. Take 'r' = 10% pa.

**Comment by yuktikhurana** [comment]
we need to initialise the object with the block.

**Comment by segunadeleye** [comment]
Fixed!

**Comment by yuktikhurana** [comment]
can we try doing it without using instance_eval ?

**Comment by segunadeleye** [comment]
Fixed.

**Comment by yuktikhurana** [comment]
looks good
