### ISSUE TITLE
Exercise 12: Character Count - Range

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/ruby_track#19]
https://github.com/segunadeleye/ruby_track/blob/master/Ex12/lib/string.rb
https://github.com/segunadeleye/ruby_track/tree/master/Ex12/bin/main.rb

Write a method that returns the no of various lowercase, uppercase, digits and special characters used in the string. Make use of Ranges.

**Comment by abhishekjain16** [comment]
Use directory Structure as discussed

**Comment by abhishekjain16** [comment]
Can we not display output with format, as discussed formatting can be done in main.rb.
Plus instead of returning count for all 4, can we return hash for count.

Something like: {lowercase: 4, uppercase: 2} ?

**Comment by segunadeleye** [comment]
Fixed.

**Comment by abhishekjain16** [comment]
Looks better now
