### ISSUE TITLE
Exercise 2: Replace - Regex

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/ruby_track#2]
https://github.com/segunadeleye/ruby_track/blob/master/Ex2/lib/string.rb
https://github.com/segunadeleye/ruby_track/blob/master/Ex2/bin/main.rb

Ask user to enter text. Replace each vowel in the text with a '*' using regular expression.

**Comment by yuktikhurana** [comment]
1. Why are we creating a replacement class ? Can't we use the built in classes ? 
2. follow directory structure.

**Comment by segunadeleye** [comment]
Fixed.

**Comment by yuktikhurana** [comment]
looks good
