### ISSUE TITLE
Exercise 22: Name - Raise

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/ruby_track#20]
https://github.com/segunadeleye/ruby_track/blob/master/Ex22/bin/main.rb
https://github.com/segunadeleye/ruby_track/blob/master/Ex22/lib/name.rb
https://github.com/segunadeleye/ruby_track/blob/master/Ex22/lib/empty_field_error.rb
https://github.com/segunadeleye/ruby_track/blob/master/Ex22/lib/first_name_error.rb

Create a class 'Name' with two attributes firstname and lastname. Neither of them can be blank and the first letter of firstname must be capital. Implement using 'raise'.Try using custom Exceptions.

**Comment by Shruti2791** [comment]
1) Ruby already provides a #empty? . Read about it.
2) Should #validate method be involved in printing the result also ?
3) Can #capitalized? method be made simpler ?

**Comment by segunadeleye** [comment]
Fixed.

**Comment by Shruti2791** [comment]
1) You should assign instances only when the values are valid. Then you will not have to call valid separately in main.rb . 
2) Can #capitalized? method be simplified ?

**Comment by segunadeleye** [comment]
Fixed.

I moved `raise` to #initialize. And I removed #validate

**Comment by Shruti2791** [comment]
1) Why can't we keep the validation in the validate method as before and just call it here in initialize ?
2) We need to print the first and last name.

**Comment by segunadeleye** [comment]
Fixed.

**Comment by Shruti2791** [comment]
Looks good :+1:
