### ISSUE TITLE
Reverse Iterate

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/ruby_track#23]
https://github.com/segunadeleye/ruby_track/blob/master/reverse_iterate/lib/array.rb
https://github.com/segunadeleye/ruby_track/blob/master/reverse_iterate/bin/main.rb
Implement a reverse iteration function for Array such that I should be able to do this

`[2,4,6,8].reverse_iterate { |i| print "#{i} "}`

It would print `8 6 4 2`

Do not use any existing iterator for this.

**Comment by yuktikhurana** [comment]
Output not as expected.

**Comment by segunadeleye** [comment]
Corrected.

**Comment by yuktikhurana** [comment]
looks good
