### ISSUE TITLE
Exercise 4: Palindrome

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/ruby_track#4]
https://github.com/segunadeleye/ruby_track/blob/master/Ex4/lib/string.rb
https://github.com/segunadeleye/ruby_track/blob/master/Ex4/bin/main.rb

Output whether the input string is palindrome. The program quits when user enters 'q/Q'

**Comment by abhishekjain16** [comment]
Use directory Structure as discussed

**Comment by abhishekjain16** [comment]
1. Use better name for method check.
2. palindrome?(self) why are we passing self in instance method.

**Comment by segunadeleye** [comment]
Fixed.
