### ISSUE TITLE
Exercise 5: Customer Account Balance

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/ruby_track#5]
https://github.com/segunadeleye/ruby_track/blob/master/Ex5/lib/customer.rb
https://github.com/segunadeleye/ruby_track/blob/master/Ex5/bin/main.rb

Define a class Customer having three variables "name","account_no" & "balance". It must initialise the class object with the name of the customer, auto­increment the account no and set balance to 1000. Define methods deposit() and withdraw() for this class.

**Comment by Shruti2791** [comment]
1) Correct the directory structure.
2) No check for depositing and withdrawing -ve amount.
3) Why do we need to pass @balace to #transaction_details .
4) Method name should rather be show_transaction_details. Isn't it ?
5) Line no. 7 can be simplified.

**Comment by segunadeleye** [comment]
Fixed

**Comment by Shruti2791** [comment]
Use require_relative.
Else looks fine.
