### ISSUE TITLE
Exercise 6: Vehicle - Subclass

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/ruby_track#6]
https://github.com/segunadeleye/ruby_track/blob/master/Ex6/lib/vehicle.rb
https://github.com/segunadeleye/ruby_track/blob/master/Ex6/lib/bike.rb
https://github.com/segunadeleye/ruby_track/blob/master/Ex6/bin/main.rb

Define a class named 'Vehicle' consisting of 'name','price' and methods for initialising and showingcontents. The 'price' of Vehicle may change over time. Now create a subclass 'Bike' having 'dealer' and method to show its content. Initialise a Bike class object with certain values and then change its price.

**Comment by Shruti2791** [comment]
Correct the directory structure

**Comment by segunadeleye** [comment]
Done.

**Comment by Shruti2791** [comment]
Looks good. :+1:
