### ISSUE TITLE
Exercise 7: Invert Case

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/ruby_track#7]
https://github.com/segunadeleye/ruby_track/blob/master/Ex7/lib/string.rb
https://github.com/segunadeleye/ruby_track/blob/master/Ex7/bin/main.rb

Overwrite the default 'to_s' method such that it inverses the case of each letter. Eg:
"hello WORLD".to_s ­> "HELLO world

**Comment by abhishekjain16** [comment]
Use directory Structure as discussed
