### ISSUE TITLE
Exercise 8: Power - Array

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/ruby_track#8]
https://github.com/segunadeleye/ruby_track/blob/master/Ex8/bin/main.rb
https://github.com/segunadeleye/ruby_track/blob/master/Ex8/lib/array.rb

efine a method power() for an array. It takes an argument 'x' and returns the array with elements raised to
power 'x'. Try to make use of array functions.

Eg: `[1,2,3,4,5,6].power(3)` -­> `[1, 8, 27, 64, 125, 216]`

**Comment by yuktikhurana** [comment]
1. directory structure
2. move presentation outside of array class. power method should just return the resulting array

**Comment by segunadeleye** [comment]
FIxed.

**Comment by yuktikhurana** [comment]
looks good
