### ISSUE TITLE
Exercise 9: Array - Hash

### ISSUE THREAD

**Issue by segunadeleye** [segunadeleye/ruby_track#9]
https://github.com/segunadeleye/ruby_track/blob/master/Ex9/bin/main.rb
https://github.com/segunadeleye/ruby_track/blob/master/Ex9/lib/array.rb

Create a method for Array that can create a hash having 'key' as length of the element and value as an array of all the elements of that length. Make use of for­in loop for the purpose.Eg: `['abc','def',1234,234,'abcd','x','mnop',5,'zZzZ']`
should give result as
`{3=>["abc", "def", 234], 4=>[1234, "abcd", "mnop", "zZzZ"], 1=>["x", 5]}`

**Comment by yuktikhurana** [comment]
1. Please follow the following directory structure
   we've a folder the exercise say array_hash
   inside that we've two folders bin and lib
   bin has a file main.rb for user interaction
   lib has class files say array.rb which holds the functionality. Name of file should match the class name. Class name to be camel case and file name to be snake case.
   So all presentation in bin and functionality goes in lib
2. Why are we checking hash has_key?. Can we initialise a hash with a default value of an empty array ?

**Comment by segunadeleye** [comment]
I posted the wrong question for this exercise. I have corrected it.

**Comment by yuktikhurana** [comment]
i checked it

**Comment by segunadeleye** [comment]
Fixed

**Comment by yuktikhurana** [comment]
looks fine
